### ISSUE TITLE
SAFE AREA ERROR

### ISSUE THREAD

**Issue by ghost** [giovannidavi/react-native-animated-screen#2] opened 2021-08-21 15:06 UTC
TypeError: Cannot read property 'initialWindowSafeAreaInsets' of undefined

This error is located at:
    in AnimatedScreenWrapper (at allProdcuts.js:12)

**Comment by giovannidavi** [comment] 2021-08-21 19:00
The issue was caused by a deprecation in one of the package dependencies. 
Resolved by [v1.1.1](https://github.com/giovannidavi/react-native-animated-screen/pull/4)

**Closed as completed** 2021-09-04 20:13 UTC
